In [1]:
import pandas as pd

In [5]:
s = pd.Series([1,2,3,4,5])

In [6]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
s2 = pd.Series([1,2,3,4], index=['a','b','c','d'])

In [8]:
s2

a    1
b    2
c    3
d    4
dtype: int64

In [9]:
s3 = pd.Series({'a':1,'b':55,'c':66})

In [11]:
s3

a     1
b    55
c    66
dtype: int64

In [14]:
s4 = pd.Series(101, index=['a','b','c','d'])

In [15]:
s4

a    101
b    101
c    101
d    101
dtype: int64

In [16]:
import numpy as np

In [25]:
s1 = pd.Series(np.arange(1,10), index=list('abcdefghi'))

In [26]:
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
i    9
dtype: int64

In [28]:
m = pd.Series([77,88,99,67,98],index=['Maths','Science','Physics','Hindi','English'])

In [29]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [33]:
m.values

array([77, 88, 99, 67, 98])

In [34]:
m.index

Index(['Maths', 'Science', 'Physics', 'Hindi', 'English'], dtype='str')

In [35]:
m.dtype

dtype('int64')

In [36]:
m.shape

(5,)

In [37]:
m.size

5

In [38]:
m.ndim

1

In [40]:
m['Maths']

np.int64(77)

In [41]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [42]:
s[3]

np.int64(4)

In [46]:
m.loc['Maths']

np.int64(77)

In [49]:
m.iloc[0]

np.int64(77)

In [51]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [52]:
m.loc['Hindi']

np.int64(67)

In [53]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [54]:
s.loc[2]

np.int64(3)

In [55]:
s.iloc[2]

np.int64(3)

In [58]:
m[['Maths','Hindi','English']]

Maths      77
Hindi      67
English    98
dtype: int64

In [59]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [60]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [61]:
s[1:4]

1    2
2    3
3    4
dtype: int64

In [62]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [67]:
m['Maths':'Hindi']

Maths      77
Science    88
Physics    99
Hindi      67
dtype: int64

In [68]:
m[0:3]

Maths      77
Science    88
Physics    99
dtype: int64

In [69]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [70]:
m>80

Maths      False
Science     True
Physics     True
Hindi      False
English     True
dtype: bool

In [71]:
m[m>80]

Science    88
Physics    99
English    98
dtype: int64

In [72]:
m[ (m>90) | (m<70) ]

Physics    99
Hindi      67
English    98
dtype: int64

In [73]:
m[ (m<90) & (m>70) ]

Maths      77
Science    88
dtype: int64

In [74]:
m+5

Maths       82
Science     93
Physics    104
Hindi       72
English    103
dtype: int64

In [75]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [76]:
m.mean()

np.float64(85.8)

In [78]:
m.max()

np.int64(99)

In [79]:
m.min()

np.int64(67)

In [80]:
m.std()

np.float64(13.773162309360911)

In [82]:
m.sum()

np.int64(429)

In [83]:
m.median()

np.float64(88.0)

In [86]:
m.idxmax()

'Physics'

In [87]:
m.idxmin()

'Hindi'

In [88]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [90]:
m.sort_values()

Hindi      67
Maths      77
Science    88
English    98
Physics    99
dtype: int64

In [91]:
m.sort_values(ascending=False)

Physics    99
English    98
Science    88
Maths      77
Hindi      67
dtype: int64

In [93]:
m.sort_index()

English    98
Hindi      67
Maths      77
Physics    99
Science    88
dtype: int64

In [94]:
m.sort_index(ascending=False)

Science    88
Physics    99
Maths      77
Hindi      67
English    98
dtype: int64

In [95]:
m.rank()

Maths      2.0
Science    3.0
Physics    5.0
Hindi      1.0
English    4.0
dtype: float64

In [97]:
m

Maths      77
Science    88
Physics    99
Hindi      67
English    98
dtype: int64

In [98]:
m.to_dict()

{'Maths': 77, 'Science': 88, 'Physics': 99, 'Hindi': 67, 'English': 98}

In [100]:
m.to_latex()

'\\begin{tabular}{lr}\n\\toprule\n & 0 \\\\\n\\midrule\nMaths & 77 \\\\\nScience & 88 \\\\\nPhysics & 99 \\\\\nHindi & 67 \\\\\nEnglish & 98 \\\\\n\\bottomrule\n\\end{tabular}\n'

In [101]:
m.to_numpy()

array([77, 88, 99, 67, 98])

# DataFrame

In [13]:
import numpy as np

In [14]:
data = {
    'Name': ['Maninder Singh', ' Harkirat', 'Sanju','Sarika','Chanchal','Deepa','Vansh','Bharti','Muskan','Anjali','Aryan'],
    'Course': ['M. Tech','BCA','BCA','MCA','MCA','B.Sc','B.Sc.','BCA','BCA','BCA',"MCA"],
    'City':['Assandh','Panipat','Karnal','Panipat','Karnal','Gharaunda','Assandh','Assandh','Karnal','Panipat','Karnal']
}

In [15]:
data

{'Name': ['Maninder Singh',
  ' Harkirat',
  'Sanju',
  'Sarika',
  'Chanchal',
  'Deepa',
  'Vansh',
  'Bharti',
  'Muskan',
  'Anjali',
  'Aryan'],
 'Course': ['M. Tech',
  'BCA',
  'BCA',
  'MCA',
  'MCA',
  'B.Sc',
  'B.Sc.',
  'BCA',
  'BCA',
  'BCA',
  'MCA'],
 'City': ['Assandh',
  'Panipat',
  'Karnal',
  'Panipat',
  'Karnal',
  'Gharaunda',
  'Assandh',
  'Assandh',
  'Karnal',
  'Panipat',
  'Karnal']}

In [16]:
df = pd.DataFrame(data)

In [17]:
df

              Name   Course       City
0   Maninder Singh  M. Tech    Assandh
1         Harkirat      BCA    Panipat
2            Sanju      BCA     Karnal
3           Sarika      MCA    Panipat
4         Chanchal      MCA     Karnal
5            Deepa     B.Sc  Gharaunda
6            Vansh    B.Sc.    Assandh
7           Bharti      BCA    Assandh
8           Muskan      BCA     Karnal
9           Anjali      BCA    Panipat
10           Aryan      MCA     Karnal

In [18]:
records = [
    {'Product': 'Laptop',  'Price': 55000, 'Stock': 25},
    {'Product': 'Phone',   'Price': 18000, 'Stock': 80},
    {'Product': 'Tablet',  'Price': 22000, 'Stock': 40},
    {'Product': 'Monitor', 'Price': 12000, 'Stock': 15},
]

In [19]:
df2 = pd.DataFrame(records)

In [20]:
df2

   Product  Price  Stock
0   Laptop  55000     25
1    Phone  18000     80
2   Tablet  22000     40
3  Monitor  12000     15

In [21]:
marks = np.random.randint(50,100,size=(4,3))

In [22]:
marks

array([[84, 70, 55],
       [87, 86, 58],
       [92, 68, 55],
       [67, 63, 85]])

In [23]:
df3 = pd.DataFrame(marks, columns=['English','Maths','Science'], index=['S1','S2','S3','S4'])

In [24]:
df3

    English  Maths  Science
S1       84     70       55
S2       87     86       58
S3       92     68       55
S4       67     63       85

In [25]:
df4 = pd.DataFrame({
    'A':pd.Series([1,2,3], index=['x','y','z']),
    'B':pd.Series([4,5,6], index = ['x','y','z'])
})

In [26]:
df4

   A  B
x  1  4
y  2  5
z  3  6

In [27]:
df

              Name   Course       City
0   Maninder Singh  M. Tech    Assandh
1         Harkirat      BCA    Panipat
2            Sanju      BCA     Karnal
3           Sarika      MCA    Panipat
4         Chanchal      MCA     Karnal
5            Deepa     B.Sc  Gharaunda
6            Vansh    B.Sc.    Assandh
7           Bharti      BCA    Assandh
8           Muskan      BCA     Karnal
9           Anjali      BCA    Panipat
10           Aryan      MCA     Karnal

In [28]:
df.shape

(11, 3)

In [29]:
df.ndim

2

In [30]:
df.size

33

In [31]:
df.index

RangeIndex(start=0, stop=11, step=1)

In [32]:
df.columns

Index(['Name', 'Course', 'City'], dtype='str')

In [33]:
df.dtypes

Name      str
Course    str
City      str
dtype: object

In [34]:
df['marks'] = [93,89,81,33,44,65,78,56,32,27,87]

In [35]:
df

              Name   Course       City  marks
0   Maninder Singh  M. Tech    Assandh     93
1         Harkirat      BCA    Panipat     89
2            Sanju      BCA     Karnal     81
3           Sarika      MCA    Panipat     33
4         Chanchal      MCA     Karnal     44
5            Deepa     B.Sc  Gharaunda     65
6            Vansh    B.Sc.    Assandh     78
7           Bharti      BCA    Assandh     56
8           Muskan      BCA     Karnal     32
9           Anjali      BCA    Panipat     27
10           Aryan      MCA     Karnal     87

In [36]:
df.dtypes

Name        str
Course      str
City        str
marks     int64
dtype: object

In [37]:
df.head(7)

             Name   Course       City  marks
0  Maninder Singh  M. Tech    Assandh     93
1        Harkirat      BCA    Panipat     89
2           Sanju      BCA     Karnal     81
3          Sarika      MCA    Panipat     33
4        Chanchal      MCA     Karnal     44
5           Deepa     B.Sc  Gharaunda     65
6           Vansh    B.Sc.    Assandh     78

In [38]:
df.tail()

      Name Course     City  marks
6    Vansh  B.Sc.  Assandh     78
7   Bharti    BCA  Assandh     56
8   Muskan    BCA   Karnal     32
9   Anjali    BCA  Panipat     27
10   Aryan    MCA   Karnal     87

In [39]:
df.tail(6)

      Name Course       City  marks
5    Deepa   B.Sc  Gharaunda     65
6    Vansh  B.Sc.    Assandh     78
7   Bharti    BCA    Assandh     56
8   Muskan    BCA     Karnal     32
9   Anjali    BCA    Panipat     27
10   Aryan    MCA     Karnal     87

In [40]:
df.head(2)

             Name   Course     City  marks
0  Maninder Singh  M. Tech  Assandh     93
1        Harkirat      BCA  Panipat     89

In [41]:
df.sample(3)

    Name Course       City  marks
2  Sanju    BCA     Karnal     81
6  Vansh  B.Sc.    Assandh     78
5  Deepa   B.Sc  Gharaunda     65

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    11 non-null     str
 1   Course  11 non-null     str
 2   City    11 non-null     str
 3   marks   11 non-null     int64
dtypes: int64(1), str(3)
memory usage: 484.0 bytes

In [43]:
df.describe()

           marks
count  11.000000
mean   62.272727
std    25.032343
min    27.000000
25%    38.500000
50%    65.000000
75%    84.000000
max    93.000000

In [44]:
df.describe(include='all')

                  Name Course    City      marks
count               11     11      11  11.000000
unique              11      5       4        NaN
top     Maninder Singh    BCA  Karnal        NaN
freq                 1      5       4        NaN
mean               NaN    NaN     NaN  62.272727
std                NaN    NaN     NaN  25.032343
min                NaN    NaN     NaN  27.000000
25%                NaN    NaN     NaN  38.500000
50%                NaN    NaN     NaN  65.000000
75%                NaN    NaN     NaN  84.000000
max                NaN    NaN     NaN  93.000000

In [45]:
df

              Name   Course       City  marks
0   Maninder Singh  M. Tech    Assandh     93
1         Harkirat      BCA    Panipat     89
2            Sanju      BCA     Karnal     81
3           Sarika      MCA    Panipat     33
4         Chanchal      MCA     Karnal     44
5            Deepa     B.Sc  Gharaunda     65
6            Vansh    B.Sc.    Assandh     78
7           Bharti      BCA    Assandh     56
8           Muskan      BCA     Karnal     32
9           Anjali      BCA    Panipat     27
10           Aryan      MCA     Karnal     87

In [48]:
df[['Name','Course']]

              Name   Course
0   Maninder Singh  M. Tech
1         Harkirat      BCA
2            Sanju      BCA
3           Sarika      MCA
4         Chanchal      MCA
5            Deepa     B.Sc
6            Vansh    B.Sc.
7           Bharti      BCA
8           Muskan      BCA
9           Anjali      BCA
10           Aryan      MCA

### loc[]

In [55]:
df.loc[1:6]

        Name Course       City  marks
1   Harkirat    BCA    Panipat     89
2      Sanju    BCA     Karnal     81
3     Sarika    MCA    Panipat     33
4   Chanchal    MCA     Karnal     44
5      Deepa   B.Sc  Gharaunda     65
6      Vansh  B.Sc.    Assandh     78

In [62]:
df.loc[1:5,('Name','Course')]

        Name Course
1   Harkirat    BCA
2      Sanju    BCA
3     Sarika    MCA
4   Chanchal    MCA
5      Deepa   B.Sc

In [63]:
df.loc[1:4,'Name':'City']

        Name Course     City
1   Harkirat    BCA  Panipat
2      Sanju    BCA   Karnal
3     Sarika    MCA  Panipat
4   Chanchal    MCA   Karnal

In [64]:
df.iloc[0:4,0:3]

             Name   Course     City
0  Maninder Singh  M. Tech  Assandh
1        Harkirat      BCA  Panipat
2           Sanju      BCA   Karnal
3          Sarika      MCA  Panipat

In [70]:
df.at[1,'Name']

' Harkirat'

In [71]:
df.iat[0,0]

'Maninder Singh'

In [72]:
df

              Name   Course       City  marks
0   Maninder Singh  M. Tech    Assandh     93
1         Harkirat      BCA    Panipat     89
2            Sanju      BCA     Karnal     81
3           Sarika      MCA    Panipat     33
4         Chanchal      MCA     Karnal     44
5            Deepa     B.Sc  Gharaunda     65
6            Vansh    B.Sc.    Assandh     78
7           Bharti      BCA    Assandh     56
8           Muskan      BCA     Karnal     32
9           Anjali      BCA    Panipat     27
10           Aryan      MCA     Karnal     87

In [75]:
df[df['marks']>90]

             Name   Course     City  marks
0  Maninder Singh  M. Tech  Assandh     93

In [78]:
df[df['Course'] == 'M. Tech']

             Name   Course     City  marks
0  Maninder Singh  M. Tech  Assandh     93

In [80]:
df[df['Course'] == 'MCA']

        Name Course     City  marks
3     Sarika    MCA  Panipat     33
4   Chanchal    MCA   Karnal     44
10     Aryan    MCA   Karnal     87

In [81]:
df[df['Course'] == 'BCA']

        Name Course     City  marks
1   Harkirat    BCA  Panipat     89
2      Sanju    BCA   Karnal     81
7     Bharti    BCA  Assandh     56
8     Muskan    BCA   Karnal     32
9     Anjali    BCA  Panipat     27

In [82]:
df[ df['City'] == 'Assandh']

             Name   Course     City  marks
0  Maninder Singh  M. Tech  Assandh     93
6           Vansh    B.Sc.  Assandh     78
7          Bharti      BCA  Assandh     56

In [84]:
df[ (df['City'] == 'Assandh') & (df['marks'] > 70)]

             Name   Course     City  marks
0  Maninder Singh  M. Tech  Assandh     93
6           Vansh    B.Sc.  Assandh     78

In [87]:
df[ (df['City'] == 'Assandh') | (df['marks'] >80) ]

              Name   Course     City  marks
0   Maninder Singh  M. Tech  Assandh     93
1         Harkirat      BCA  Panipat     89
2            Sanju      BCA   Karnal     81
6            Vansh    B.Sc.  Assandh     78
7           Bharti      BCA  Assandh     56
10           Aryan      MCA   Karnal     87

In [90]:
df[ ~(df['City'] == "Assandh")]

         Name Course       City  marks
1    Harkirat    BCA    Panipat     89
2       Sanju    BCA     Karnal     81
3      Sarika    MCA    Panipat     33
4    Chanchal    MCA     Karnal     44
5       Deepa   B.Sc  Gharaunda     65
8      Muskan    BCA     Karnal     32
9      Anjali    BCA    Panipat     27
10      Aryan    MCA     Karnal     87

In [92]:
df[ df['Course'].isin(['M. Tech', 'MCA']) ]

              Name   Course     City  marks
0   Maninder Singh  M. Tech  Assandh     93
3           Sarika      MCA  Panipat     33
4         Chanchal      MCA   Karnal     44
10           Aryan      MCA   Karnal     87

In [94]:
df[ df['marks'].between(50,80) ]

     Name Course       City  marks
5   Deepa   B.Sc  Gharaunda     65
6   Vansh  B.Sc.    Assandh     78
7  Bharti    BCA    Assandh     56

In [96]:

df.dtypes

Name        str
Course      str
City        str
marks     int64
dtype: object

In [98]:
type(df['Course'])

pandas.Series

In [100]:
type(df['Course'].str)

pandas.core.strings.accessor.StringMethods

In [103]:
df[ df['Course'].str.contains("M.") ]

              Name   Course     City  marks
0   Maninder Singh  M. Tech  Assandh     93
3           Sarika      MCA  Panipat     33
4         Chanchal      MCA   Karnal     44
10           Aryan      MCA   Karnal     87

In [106]:
df[ df['Name'].str.startswith('A') ]

      Name Course     City  marks
9   Anjali    BCA  Panipat     27
10   Aryan    MCA   Karnal     87

In [107]:
m = 75

In [110]:
df.query('marks >85')

              Name   Course     City  marks
0   Maninder Singh  M. Tech  Assandh     93
1         Harkirat      BCA  Panipat     89
10           Aryan      MCA   Karnal     87

In [111]:
df.query('marks > @m')

              Name   Course     City  marks
0   Maninder Singh  M. Tech  Assandh     93
1         Harkirat      BCA  Panipat     89
2            Sanju      BCA   Karnal     81
6            Vansh    B.Sc.  Assandh     78
10           Aryan      MCA   Karnal     87

In [113]:
df['English'] = df['marks']

In [114]:
df

              Name   Course       City  marks  English
0   Maninder Singh  M. Tech    Assandh     93       93
1         Harkirat      BCA    Panipat     89       89
2            Sanju      BCA     Karnal     81       81
3           Sarika      MCA    Panipat     33       33
4         Chanchal      MCA     Karnal     44       44
5            Deepa     B.Sc  Gharaunda     65       65
6            Vansh    B.Sc.    Assandh     78       78
7           Bharti      BCA    Assandh     56       56
8           Muskan      BCA     Karnal     32       32
9           Anjali      BCA    Panipat     27       27
10           Aryan      MCA     Karnal     87       87

In [119]:
df.drop('marks',axis=1, inplace=True)

In [120]:
df

              Name   Course       City  English
0   Maninder Singh  M. Tech    Assandh       93
1         Harkirat      BCA    Panipat       89
2            Sanju      BCA     Karnal       81
3           Sarika      MCA    Panipat       33
4         Chanchal      MCA     Karnal       44
5            Deepa     B.Sc  Gharaunda       65
6            Vansh    B.Sc.    Assandh       78
7           Bharti      BCA    Assandh       56
8           Muskan      BCA     Karnal       32
9           Anjali      BCA    Panipat       27
10           Aryan      MCA     Karnal       87

In [123]:
df['Maths'] = np.random.randint(60,100,11)

In [124]:
df

              Name   Course       City  English  Maths
0   Maninder Singh  M. Tech    Assandh       93     74
1         Harkirat      BCA    Panipat       89     84
2            Sanju      BCA     Karnal       81     60
3           Sarika      MCA    Panipat       33     60
4         Chanchal      MCA     Karnal       44     74
5            Deepa     B.Sc  Gharaunda       65     71
6            Vansh    B.Sc.    Assandh       78     68
7           Bharti      BCA    Assandh       56     94
8           Muskan      BCA     Karnal       32     72
9           Anjali      BCA    Panipat       27     70
10           Aryan      MCA     Karnal       87     64

In [125]:
df['Total'] = df['English'] + df['Maths']

In [126]:
df

              Name   Course       City  English  Maths  Total
0   Maninder Singh  M. Tech    Assandh       93     74    167
1         Harkirat      BCA    Panipat       89     84    173
2            Sanju      BCA     Karnal       81     60    141
3           Sarika      MCA    Panipat       33     60     93
4         Chanchal      MCA     Karnal       44     74    118
5            Deepa     B.Sc  Gharaunda       65     71    136
6            Vansh    B.Sc.    Assandh       78     68    146
7           Bharti      BCA    Assandh       56     94    150
8           Muskan      BCA     Karnal       32     72    104
9           Anjali      BCA    Panipat       27     70     97
10           Aryan      MCA     Karnal       87     64    151

In [128]:
df['Average'] = df['Total']/2

In [129]:
df

              Name   Course       City  English  Maths  Total  Average
0   Maninder Singh  M. Tech    Assandh       93     74    167     83.5
1         Harkirat      BCA    Panipat       89     84    173     86.5
2            Sanju      BCA     Karnal       81     60    141     70.5
3           Sarika      MCA    Panipat       33     60     93     46.5
4         Chanchal      MCA     Karnal       44     74    118     59.0
5            Deepa     B.Sc  Gharaunda       65     71    136     68.0
6            Vansh    B.Sc.    Assandh       78     68    146     73.0
7           Bharti      BCA    Assandh       56     94    150     75.0
8           Muskan      BCA     Karnal       32     72    104     52.0
9           Anjali      BCA    Panipat       27     70     97     48.5
10           Aryan      MCA     Karnal       87     64    151     75.5

In [157]:
d1 = pd.DataFrame([['Vikrant', 'M. Tech', 'Panipat', 81, 90, (81+90), ((81+90)/2)]], columns=list(df.columns))

In [152]:
df.columns.values

array(['Name', 'Course', 'City', 'English', 'Maths', 'Total', 'Average'],
      dtype=object)

In [158]:
df = pd.concat([df, d1], ignore_index=True)

In [159]:
df

              Name   Course       City  English  Maths  Total  Average
0   Maninder Singh  M. Tech    Assandh     93.0   74.0  167.0     83.5
1         Harkirat      BCA    Panipat     89.0   84.0  173.0     86.5
2            Sanju      BCA     Karnal     81.0   60.0  141.0     70.5
3           Sarika      MCA    Panipat     33.0   60.0   93.0     46.5
4         Chanchal      MCA     Karnal     44.0   74.0  118.0     59.0
5            Deepa     B.Sc  Gharaunda     65.0   71.0  136.0     68.0
6            Vansh    B.Sc.    Assandh     78.0   68.0  146.0     73.0
7           Bharti      BCA    Assandh     56.0   94.0  150.0     75.0
8           Muskan      BCA     Karnal     32.0   72.0  104.0     52.0
9           Anjali      BCA    Panipat     27.0   70.0   97.0     48.5
10           Aryan      MCA     Karnal     87.0   64.0  151.0     75.5
11         Vikrant  M. Tech    Panipat     81.0   90.0  171.0     85.5

In [142]:
df = df.drop(range(11,18))

In [143]:
df

              Name   Course       City  English  Maths  Total  Average    0
0   Maninder Singh  M. Tech    Assandh     93.0   74.0  167.0     83.5  NaN
1         Harkirat      BCA    Panipat     89.0   84.0  173.0     86.5  NaN
2            Sanju      BCA     Karnal     81.0   60.0  141.0     70.5  NaN
3           Sarika      MCA    Panipat     33.0   60.0   93.0     46.5  NaN
4         Chanchal      MCA     Karnal     44.0   74.0  118.0     59.0  NaN
5            Deepa     B.Sc  Gharaunda     65.0   71.0  136.0     68.0  NaN
6            Vansh    B.Sc.    Assandh     78.0   68.0  146.0     73.0  NaN
7           Bharti      BCA    Assandh     56.0   94.0  150.0     75.0  NaN
8           Muskan      BCA     Karnal     32.0   72.0  104.0     52.0  NaN
9           Anjali      BCA    Panipat     27.0   70.0   97.0     48.5  NaN
10           Aryan      MCA     Karnal     87.0   64.0  151.0     75.5  NaN

In [146]:
df.dropna(how='all', axis=1, inplace=True)

In [147]:
df

              Name   Course       City  English  Maths  Total  Average
0   Maninder Singh  M. Tech    Assandh     93.0   74.0  167.0     83.5
1         Harkirat      BCA    Panipat     89.0   84.0  173.0     86.5
2            Sanju      BCA     Karnal     81.0   60.0  141.0     70.5
3           Sarika      MCA    Panipat     33.0   60.0   93.0     46.5
4         Chanchal      MCA     Karnal     44.0   74.0  118.0     59.0
5            Deepa     B.Sc  Gharaunda     65.0   71.0  136.0     68.0
6            Vansh    B.Sc.    Assandh     78.0   68.0  146.0     73.0
7           Bharti      BCA    Assandh     56.0   94.0  150.0     75.0
8           Muskan      BCA     Karnal     32.0   72.0  104.0     52.0
9           Anjali      BCA    Panipat     27.0   70.0   97.0     48.5
10           Aryan      MCA     Karnal     87.0   64.0  151.0     75.5

In [148]:
d1

         0
0  Vikrant
1  M. Tech
2  Panipat
3       81
4       90
5      171
6     85.5

In [160]:
df

              Name   Course       City  English  Maths  Total  Average
0   Maninder Singh  M. Tech    Assandh     93.0   74.0  167.0     83.5
1         Harkirat      BCA    Panipat     89.0   84.0  173.0     86.5
2            Sanju      BCA     Karnal     81.0   60.0  141.0     70.5
3           Sarika      MCA    Panipat     33.0   60.0   93.0     46.5
4         Chanchal      MCA     Karnal     44.0   74.0  118.0     59.0
5            Deepa     B.Sc  Gharaunda     65.0   71.0  136.0     68.0
6            Vansh    B.Sc.    Assandh     78.0   68.0  146.0     73.0
7           Bharti      BCA    Assandh     56.0   94.0  150.0     75.0
8           Muskan      BCA     Karnal     32.0   72.0  104.0     52.0
9           Anjali      BCA    Panipat     27.0   70.0   97.0     48.5
10           Aryan      MCA     Karnal     87.0   64.0  151.0     75.5
11         Vikrant  M. Tech    Panipat     81.0   90.0  171.0     85.5

In [162]:
df.assign(Percentage = lambda x:(x['Average']/100) * 100,
           Rank = lambda x: x['Average'].rank(ascending=False).astype(int))

,Name,Course,City,English,Maths,Total,Average,Percentage,Rank
0,Maninder Singh,M. Tech,Assandh,93.0,74.0,167.0,83.5,83.5,3
1,Harkirat,BCA,Panipat,89.0,84.0,173.0,86.5,86.5,1
2,Sanju,BCA,Karnal,81.0,60.0,141.0,70.5,70.5,7
3,Sarika,MCA,Panipat,33.0,60.0,93.0,46.5,46.5,12
4,Chanchal,MCA,Karnal,44.0,74.0,118.0,59.0,59.0,9
5,Deepa,B.Sc,Gharaunda,65.0,71.0,136.0,68.0,68.0,8
6,Vansh,B.Sc.,Assandh,78.0,68.0,146.0,73.0,73.0,6
7,Bharti,BCA,Assandh,56.0,94.0,150.0,75.0,75.0,5
8,Muskan,BCA,Karnal,32.0,72.0,104.0,52.0,52.0,10
9,Anjali,BCA,Panipat,27.0,70.0,97.0,48.5,48.5,11
10,Aryan,MCA,Karnal,87.0,64.0,151.0,75.5,75.5,4
11,Vikrant,M. Tech,Panipat,81.0,90.0,171.0,85.5,85.5,2

In [165]:
df['Roll'] = range(101,113)

In [166]:
df

              Name   Course       City  English  Maths  Total  Average  Roll
0   Maninder Singh  M. Tech    Assandh     93.0   74.0  167.0     83.5   101
1         Harkirat      BCA    Panipat     89.0   84.0  173.0     86.5   102
2            Sanju      BCA     Karnal     81.0   60.0  141.0     70.5   103
3           Sarika      MCA    Panipat     33.0   60.0   93.0     46.5   104
4         Chanchal      MCA     Karnal     44.0   74.0  118.0     59.0   105
5            Deepa     B.Sc  Gharaunda     65.0   71.0  136.0     68.0   106
6            Vansh    B.Sc.    Assandh     78.0   68.0  146.0     73.0   107
7           Bharti      BCA    Assandh     56.0   94.0  150.0     75.0   108
8           Muskan      BCA     Karnal     32.0   72.0  104.0     52.0   109
9           Anjali      BCA    Panipat     27.0   70.0   97.0     48.5   110
10           Aryan      MCA     Karnal     87.0   64.0  151.0     75.5   111
11         Vikrant  M. Tech    Panipat     81.0   90.0  171.0     85.5   112

In [170]:
df.set_index('Roll', inplace=True)

In [171]:
df

                Name   Course       City  English  Maths  Total  Average
Roll
101   Maninder Singh  M. Tech    Assandh     93.0   74.0  167.0     83.5
102         Harkirat      BCA    Panipat     89.0   84.0  173.0     86.5
103            Sanju      BCA     Karnal     81.0   60.0  141.0     70.5
104           Sarika      MCA    Panipat     33.0   60.0   93.0     46.5
105         Chanchal      MCA     Karnal     44.0   74.0  118.0     59.0
106            Deepa     B.Sc  Gharaunda     65.0   71.0  136.0     68.0
107            Vansh    B.Sc.    Assandh     78.0   68.0  146.0     73.0
108           Bharti      BCA    Assandh     56.0   94.0  150.0     75.0
109           Muskan      BCA     Karnal     32.0   72.0  104.0     52.0
110           Anjali      BCA    Panipat     27.0   70.0   97.0     48.5
111            Aryan      MCA     Karnal     87.0   64.0  151.0     75.5
112          Vikrant  M. Tech    Panipat     81.0   90.0  171.0     85.5

In [177]:
df.reset_index(inplace=True)

In [178]:
df

,index,Roll,Name,Course,City,English,Maths,Total,Average
0,0,101,Maninder Singh,M. Tech,Assandh,93.0,74.0,167.0,83.5
1,1,102,Harkirat,BCA,Panipat,89.0,84.0,173.0,86.5
2,2,103,Sanju,BCA,Karnal,81.0,60.0,141.0,70.5
3,3,104,Sarika,MCA,Panipat,33.0,60.0,93.0,46.5
4,4,105,Chanchal,MCA,Karnal,44.0,74.0,118.0,59.0
5,5,106,Deepa,B.Sc,Gharaunda,65.0,71.0,136.0,68.0
6,6,107,Vansh,B.Sc.,Assandh,78.0,68.0,146.0,73.0
7,7,108,Bharti,BCA,Assandh,56.0,94.0,150.0,75.0
8,8,109,Muskan,BCA,Karnal,32.0,72.0,104.0,52.0
9,9,110,Anjali,BCA,Panipat,27.0,70.0,97.0,48.5
10,10,111,Aryan,MCA,Karnal,87.0,64.0,151.0,75.5
11,11,112,Vikrant,M. Tech,Panipat,81.0,90.0,171.0,85.5